### ISSUE TITLE
Provide Release Info JSON

### ISSUE THREAD

**Issue by Fleshgrinder** [corretto/corretto-downloads#3]
This is a split from https://github.com/corretto/corretto-17/issues/62 as I need some tracking issue for this. 😉

## Use Case

We want to automatically provision build machines with the current Corretto releases, and would like to do so in a fully automatic and unattended manner until the end of time (or the signing key is switched).

## Current Behavior

We have https://corretto.github.io/corretto-downloads/latest_links/indexmap_with_checksum.json which allows us to dynamically resolve the releases. However, it lists all versions without any additional information on whether these are still supported or what the level of support is. Given that the Corretto releases have a fixed download link pattern (thanks for that ❤️) there is also no real need to resolve downloads with this JSON file, it actually would be sufficient to know which versions are available.

    https://corretto.aws/[latest/latest_checksum]/amazon-corretto-[corretto_version]-[cpu_arch]-[os]-[package_type].[file_extension]

> 💡 The index map is still useful for anyone who needs to support many operating systems, as it allows one to check what kind of releases are available. It is just not required for us, because we use Lib-C Linux where everything is available, always.

## Expected Behavior

Eclipse has https://api.adoptium.net/v3/info/available_releases with the following content at the time of writing this issue:

```json
{
  "available_lts_releases": [
    8,
    11,
    17
  ],
  "available_releases": [
    8,
    11,
    16,
    17,
    18
  ],
  "most_recent_feature_release": 18,
  "most_recent_feature_version": 19,
  "most_recent_lts": 17,
  "tip_version": 19
}
```

A file like this provides all the necessary information to know what is available and can neatly be combined with the fixed download link pattern to resolve everything. A similar file for Corretto could look as follows at the time of writing:

```json
{
  "available_lts_releases": [
    8,
    11,
    17
  ],
  "available_releases": [
    8,
    11,
    15,
    16,
    17,
    18
  ],
  "most_recent_lts_release": 17,
  "most_recent_release": 18
}
```

Given that Corretto (at least not so far) provides unstable builds we could leave out a few things that Eclipse has.

> 🔥 It is important that the file uses numbers, as this makes processing with tools like `jq` much simpler. Strings would require additional unnecessary massaging.

**Comment by lutkerd** [comment]
[version](https://github.com/corretto/corretto-downloads/blob/main/latest_links/version-info.json) should have required information.
